version: "2"
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - private_network
    redis:
        container_name: redis
        image: redis:3.2-alpine
        networks:
            - private_network
networks:
    private_network:
        driver: bridge